"""Unit tests for the embedded input provenance header (Phase 5 / B4).

Every generated CP2K input carries a deterministic comment header recording the
key generation parameters, so the file is self-describing and reproducible
without external docs (FAIR R1.2). The header must stay deterministic so it does
not break regression baselines or reproducibility.
"""

from pathlib import Path

import pytest

import charmmgui2cp2k as c

pytestmark = pytest.mark.unit

_FIX = Path(__file__).resolve().parent.parent / "fixtures"


def _build_qmmm_input(run_type="GEO_OPT"):
    topo, coords, box, emap, _u, alias = c._step2_parse_topology(
        str(_FIX / "ala_dipeptide.parm7"), str(_FIX / "ala_dipeptide.rst7"))
    qm_elements, qm_indices, _m, _l = c._step3_extract_qm_from_mdin(
        str(_FIX / "ala_dipeptide_qmmm.mdin"), topo, emap, list(alias.atom_aliases),
        prmtop_path=str(_FIX / "ala_dipeptide.parm7"),
        crd_path=str(_FIX / "ala_dipeptide.rst7"))
    links, adj = c._step4_detect_links(topo, qm_indices, emap)
    charges_e = [q / c.AMBER_CHARGE_SCALE for q in topo.get_float_array("CHARGE")[: topo.natom]]
    c.enrich_link_with_m2(links, adj, set(qm_indices), charges_e)
    qmmm_pp = c.make_qmmm_periodic_policy()
    qm_cell_abc, _ = c.compute_qm_cell(list(qm_indices), coords,
                                       padding=qmmm_pp.qm_cell_padding, box_dims=box,
                                       qmmm_periodic_policy=qmmm_pp)
    qm_kinds, _ = c.generate_qm_kinds(qm_elements, basis_set="DZVP-MOLOPT-GTH", use_admm=True)
    plan = c.build_residual_charge_plan(qm_indices, topo,
                                        m1_set={int(l["MM_INDEX"]) for l in links}, coords=coords)
    override = c._apply_residual_charge_plan_to_raw_charges(topo.get_float_array("CHARGE"), plan)
    mm = c.collect_topology_variant_data(topo, list(qm_elements.keys()), alias_plan=alias)
    qmmm = c.collect_topology_variant_data(topo, list(qm_elements.keys()),
                                           charge_array_override=override, alias_plan=alias)
    rec, _ = c.recommended_scf_profile(qm_elements.keys(), "B3LYP",
                                       sum(len(v) for v in qm_elements.values()), multiplicity=1)
    scf = dict(c.SCF_PROFILES[rec])
    sm = c.make_system_spec(
        prmtop_file="system_qmmm.prmtop", xyz_file="system.xyz", box_dims=box,
        qm_elements=qm_elements, link_bonds=list(links), qm_kinds_lines=qm_kinds,
        mm_kinds_lines=mm["mm_kinds"], mm_stage_kinds_lines=mm["mm_kinds"],
        qmmm_stage_kinds_lines=qmmm["mm_kinds"], mm_prmtop_file="system_mm.prmtop",
        qmmm_prmtop_file="system_qmmm.prmtop", qmmm_periodic_policy=qmmm_pp,
        qm_cell_abc=qm_cell_abc, qm_charge=0, multiplicity=1, natom=topo.natom)
    dft = c.make_dft_config(
        functional="B3LYP", basis_set="DZVP-MOLOPT-GTH", cutoff=500, rel_cutoff=60,
        use_admm=True, scf_profile=rec, scf_max_scf=scf["max_scf"], scf_eps_scf=scf["eps_scf"],
        scf_guess=scf["scf_guess"], scf_cholesky=scf.get("cholesky"),
        qs_eps_default=scf.get("qs_eps_default"), scf_added_mos=scf["added_mos"],
        scf_mixing_method=scf["mixing_method"], scf_mixing_alpha=scf["mixing_alpha"],
        scf_nbroyden=scf["nbroyden"], outer_max_scf=scf["outer_max_scf"],
        outer_eps_scf=scf["outer_eps_scf"], qm_elements_for_admm=qm_elements,
        qm_kinds_lines_for_admm=qm_kinds)
    rc = c.make_run_config(project_name="hdr_test", run_type=run_type)
    return c.assemble_cp2k_input(sm, dft, rc)


def test_header_present_and_records_key_parameters():
    inp = _build_qmmm_input()
    assert f"Generated by charmmgui2cp2k v{c.__version__}" in inp
    assert "run_type              : GEO_OPT" in inp
    assert "functional            : B3LYP" in inp
    assert "boundary_charge_scheme: CHARGE_SHIFT" in inp
    assert "qm_charge             : 0" in inp
    assert "multiplicity          : 1" in inp


def test_header_is_comment_only_before_global():
    inp = _build_qmmm_input()
    # Everything before &GLOBAL must be CP2K comment lines (start with ! or blank).
    pre = inp.split("&GLOBAL", 1)[0].splitlines()
    assert any(line.strip().startswith("!") for line in pre)
    assert all((not line.strip()) or line.lstrip().startswith("!") for line in pre)


def test_header_is_deterministic():
    assert _build_qmmm_input() == _build_qmmm_input()


def test_header_function_no_timestamp_or_env_versions():
    # Determinism guard: the embedded header must not leak volatile tokens.
    inp = _build_qmmm_input()
    head = inp.split("&GLOBAL", 1)[0].lower()
    for tok in ("textual", "/home/", "20260", "20261", "cpu", "gpu"):
        assert tok not in head, f"volatile token {tok!r} leaked into the header"
